(deftheme adwaita-SP
  "Created 2017-05-31.")

(custom-theme-set-faces
 'adwaita-SP
 '(fringe ((((class color) (min-colors 89)) (:background "#E6E6E6"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width -1 :style released-button) :background "white" :foreground "#2E3436"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#C6C6C6" :background "white"))))
 '(header-line ((t (:background "#EDEDED" :foreground "#2E3436"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#0084C8" :bold t))))
 '(region ((t (:background "RoyalBlue4" :foreground "white"))))
 '(dired-header ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(widget-button ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(success ((((class color) (min-colors 89)) (:bold t :foreground "#4E9A06"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#CE5C00"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#B50000"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#A020F0"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#0084C8" :bold t))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#F5666D" :bold t))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#0066CC"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#6799CC"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "white" :background "#4A90D9"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "white" :background "#77A4DD"))))
 '(default ((((class color) (min-colors 89)) (:background "#EDEDED" :foreground "#2E3436"))))

 ;; My Customization begins here
 '(cursor ((t (:background "dark blue"))))
 '(font-lock-comment-face ((t (:inherit shadow :foreground "grey50"))))
 '(font-lock-constant-face ((t (:foreground "RoyalBlue3"))))
 '(font-lock-function-name-face ((t (:foreground "black" :weight normal))))
 '(font-lock-keyword-face ((t (:foreground "Blue" :weight bold))))
 '(font-lock-string-face ((t (:foreground "OrangeRed4"))))
 '(font-lock-type-face ((t (:foreground "ForestGreen" :weight normal))))
 '(font-latex-bold-face ((t (:inherit bold :foreground "black"))))
 '(font-latex-italic-face ((t (:inherit italic :foreground "black"))))
 '(font-latex-math-face ((t (:foreground "dark red"))))
 '(font-latex-sectioning-2-face ((t (:inherit font-latex-sectioning-3-face))))
 '(font-latex-sectioning-3-face ((t (:inherit font-latex-sectioning-4-face))))
 '(font-latex-sectioning-4-face ((t (:inherit font-latex-sectioning-5-face))))
 '(font-latex-sectioning-5-face ((t (:foreground "black" :weight bold))))
 '(font-latex-sedate-face ((t (:foreground "Blue" :weight bold))))
 '(font-latex-subscript-face ((t nil)))
 '(font-latex-superscript-face ((t nil)))
 '(helm-buffer-directory ((t (:foreground "blue1" :weight bold))))
 '(helm-buffer-file ((t (:foreground "black"))))
 '(helm-ff-directory ((t (:foreground "blue1" :weight bold))))
 '(helm-ff-dotted-directory ((t (:foreground "gray40"))))
 '(helm-ff-executable ((t (:foreground "black"))))
 '(helm-ff-file ((t (:foreground "black"))))
 '(helm-selection ((t (:background "#C2D5E9" :distant-foreground "black"))))
 '(helm-source-header ((t (:background "RoyalBlue4" :foreground "white" :weight bold :height 1.2))))
 '(helm-visible-mark ((t (:background "#C2D5E9"))))
 '(isearch-fail ((t (:background "dark red" :foreground "white"))))
 '(org-agenda-calendar-event ((t (:foreground "black"))))
 '(org-agenda-current-time ((t (:foreground "black"))) t)
 '(org-agenda-date ((t (:inherit org-agenda-structure))) t)
 '(org-agenda-date-today ((t (:inherit org-agenda-date :slant italic))) t)
 '(org-agenda-date-weekend ((t (:inherit org-agenda-date))) t)
 '(org-agenda-structure ((t (:foreground "RoyalBlue1" :underline t :weight bold))))
 '(org-document-info ((t (:foreground "midnight blue" :slant italic))))
 '(org-document-info-keyword ((t (:foreground "RoyalBlue1"))))
 '(org-document-title ((t (:foreground "midnight blue" :weight bold))))
 '(org-done ((t (:foreground "SlateGray4" :weight bold))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-meta-line ((t (:inherit shadow))))
 '(org-time-grid ((t (:foreground "black"))))
 '(outline-1 ((t (:foreground "RoyalBlue4" :weight bold))))
 '(outline-2 ((t (:foreground "DarkOrange4"))))
 '(outline-3 ((t (:foreground "dark olive green"))))
 '(outline-4 ((t (:foreground "RoyalBlue4"))))
 '(outline-5 ((t (:foreground "DarkOrange4"))))

 ;; Original Setting
 ;; '(cursor ((((class color) (min-colors 89)) (:background "#00BBFF"))))
 ;; '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#F5666D"))))
 ;; '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#204A87"))))
 ;; '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#00578E" :bold t))))
 ;; '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold t :foreground "#A52A2A"))))
 ;; '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#4E9A06"))))
 ;; '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#2F8B58" :bold t))))
 ;; '(region ((((class color) (min-colors 89)) (:foreground unspecified :background "#C2D5E9"))))
 )

(provide-theme 'adwaita-SP)
